name: Python Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  backend-check:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ./backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          backend/requirements/default.txt
          backend/requirements/dev.txt

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements/default.txt
        pip install -r backend/requirements/dev.txt

    - name: Run Tests
      uses: koenhagen/measure-energy-action@v0.33
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: py.test -o junit_family=xunit2 -xv --ff backend/tests/unit
        count: 1
        bash: 'True'
